<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="18615" started-at="2020-05-24T12:46:55 IST" finished-at="2020-05-24T12:47:13 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="18615" started-at="2020-05-24T12:46:55 IST" finished-at="2020-05-24T12:47:13 IST">
      <class name="com.lakme.Testcases.BasesetupTestCases">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.lakme.Testcases.BasesetupTestCases@13b6aecc]" name="setup" is-config="true" duration-ms="6912" started-at="2020-05-24T12:46:55 IST" finished-at="2020-05-24T12:47:02 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.lakme.Testcases.BasesetupTestCases@13b6aecc]" name="teardown" is-config="true" duration-ms="877" started-at="2020-05-24T12:47:12 IST" finished-at="2020-05-24T12:47:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.lakme.Testcases.BasesetupTestCases -->
      <class name="com.lakme.Testcases.FlightsPageTestcases">
        <test-method status="PASS" signature="initObjects()[pri:0, instance:com.lakme.Testcases.FlightsPageTestcases@158a8276]" name="initObjects" is-config="true" duration-ms="32" started-at="2020-05-24T12:47:02 IST" finished-at="2020-05-24T12:47:02 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initObjects -->
        <test-method status="FAIL" signature="selectOneWayOptionTest()[pri:1, instance:com.lakme.Testcases.FlightsPageTestcases@158a8276]" name="selectOneWayOptionTest" duration-ms="12" started-at="2020-05-24T12:47:02 IST" finished-at="2020-05-24T12:47:02 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.lakme.Testcases.FlightsPageTestcases.selectOneWayOptionTest(FlightsPageTestcases.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectOneWayOptionTest -->
        <test-method status="PASS" signature="roundTripOptionTest()[pri:2, instance:com.lakme.Testcases.FlightsPageTestcases@158a8276]" name="roundTripOptionTest" duration-ms="5592" started-at="2020-05-24T12:47:02 IST" finished-at="2020-05-24T12:47:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- roundTripOptionTest -->
        <test-method status="PASS" signature="multicityOptionTest()[pri:3, instance:com.lakme.Testcases.FlightsPageTestcases@158a8276]" name="multicityOptionTest" duration-ms="5119" started-at="2020-05-24T12:47:07 IST" finished-at="2020-05-24T12:47:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multicityOptionTest -->
      </class> <!-- com.lakme.Testcases.FlightsPageTestcases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
