<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-05-26T14:29:27 IST" name="Suite" finished-at="2020-05-26T14:29:38 IST" duration-ms="10429">
    <groups>
    </groups>
    <test started-at="2020-05-26T14:29:27 IST" name="Test" finished-at="2020-05-26T14:29:38 IST" duration-ms="10429">
      <class name="com.lakme.Testcases.BasesetupTestCases">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.lakme.Testcases.BasesetupTestCases@282cb7c7]" started-at="2020-05-26T14:29:27 IST" name="setup" finished-at="2020-05-26T14:29:37 IST" duration-ms="9087" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.lakme.Testcases.BasesetupTestCases@282cb7c7]" started-at="2020-05-26T14:29:37 IST" name="teardown" finished-at="2020-05-26T14:29:38 IST" duration-ms="696" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.lakme.Testcases.BasesetupTestCases -->
      <class name="com.lakme.Testcases.FlightsPageTestcases">
        <test-method is-config="true" signature="initObjects()[pri:0, instance:com.lakme.Testcases.FlightsPageTestcases@7d898981]" started-at="2020-05-26T14:29:37 IST" name="initObjects" finished-at="2020-05-26T14:29:37 IST" duration-ms="44" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initObjects -->
        <test-method signature="selectOneWayOptionTest()[pri:1, instance:com.lakme.Testcases.FlightsPageTestcases@7d898981]" started-at="2020-05-26T14:29:37 IST" name="selectOneWayOptionTest" finished-at="2020-05-26T14:29:37 IST" duration-ms="32" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.lakme.Testcases.FlightsPageTestcases.selectOneWayOptionTest(FlightsPageTestcases.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectOneWayOptionTest -->
        <test-method signature="roundTripOptionTest()[pri:2, instance:com.lakme.Testcases.FlightsPageTestcases@7d898981]" started-at="2020-05-26T14:29:37 IST" name="roundTripOptionTest" finished-at="2020-05-26T14:29:37 IST" duration-ms="354" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- roundTripOptionTest -->
        <test-method signature="multicityOptionTest()[pri:3, instance:com.lakme.Testcases.FlightsPageTestcases@7d898981]" started-at="2020-05-26T14:29:37 IST" name="multicityOptionTest" finished-at="2020-05-26T14:29:37 IST" duration-ms="123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multicityOptionTest -->
      </class> <!-- com.lakme.Testcases.FlightsPageTestcases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
